name: "Destruction"

on: 
- workflow_dispatch

jobs:
  destroy-the-infrastructure:
    runs-on: ubuntu-latest
    environment: azure-env
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
    - name: Terraform Destroy
      id: Destroy
      run: terraform apply -destroy -auto-approve
