name: "Learning terraform azure with github actions"

on: 
- push
- workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: azure-env
    env:
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
    steps:
      #    - name: "Azure login"
      #      uses: azure/login@v1
      #      with:
      #        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true
